In [2]:
import tensorflow as tf           # create graph # run graph (sess.run)

In [3]:
# constant cannot modify
a = tf.constant('Hello')
b = tf.constant(10)
c = tf.constant(10.)

with tf.Session() as sess:
    print(a, sess.run(a), type(sess.run(a))) # bytes
    print(b, sess.run(b), type(sess.run(a))) # bytes
    print(c, sess.run(c), type(sess.run(c))) # np.float
    print( sess.run([a,b,c]), type(sess.run([a,b,c])) )         # list
    print( sess.run(tf.add(b,b)), type(sess.run(tf.add(b,b))) ) # np.int # int cannot add float

Tensor("Const:0", shape=(), dtype=string) b'Hello' <class 'bytes'>
Tensor("Const_1:0", shape=(), dtype=int32) 10 <class 'bytes'>
Tensor("Const_2:0", shape=(), dtype=float32) 10.0 <class 'numpy.float32'>
[b'Hello', 10, 10.0] <class 'list'>
20 <class 'numpy.int32'>


In [5]:
# placeholder cannot initialize
C = tf.placeholder(tf.int64)
D = tf.placeholder(tf.int64)
E = tf.placeholder(tf.int64)
adder = D + E

with tf.Session() as sess:
    for i in range(5):
        print(sess.run(C, {C:i}), end=' ')
    
    print( sess.run(adder, {C:10, D:20, E:30}) )    # 可以一次填充所有的占位符 # 50
    print( sess.run(adder, {D:20, E:30}) )          # 或者只填充計算所需要的 # 50
    #print( sess.run(adder, {E:30} )                # Error! 每次執行sess.run()都要填充
    print( sess.run(adder, {D:[1,3], E:[2,8]}) )    # type error

0 1 2 3 4 50
50
[ 3 11]


In [6]:
# variable must initialize and can be reassigned
W = tf.Variable([.3])
b = tf.Variable([-.3])
x = tf.placeholder(tf.float32)
linear_model = W * x + b

y = tf.placeholder(tf.float32)
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)

with tf.Session() as sess:
    sess.run( tf.global_variables_initializer() )
    print(sess.run(linear_model, {x:[1,2,3,4]}))
    print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))

    fixW = tf.assign(W, [-1.]) # deep copy fixW 
    fixb = tf.assign(b, [1.])  # deep copy fixb
    sess.run([fixW, fixb])     # replace W as fixW and b as fixb for all functions 
    print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))

[0.         0.3        0.6        0.90000004]
23.66
0.0


In [7]:
# linear regression example

# 模型參數
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)

# 輸入與輸出的資料
x = tf.placeholder(tf.float32)
linear_model = W * x + b
y = tf.placeholder(tf.float32)

# loss function
loss = tf.reduce_sum(tf.square(linear_model - y)) # sum of the squares

# optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

# training data
x_train = [1, 2, 3, 4]
y_train = [0, -1, -2, -3]

with tf.Session() as sess:
    sess.run( tf.global_variables_initializer() )

    for i in range(1000):
        sess.run(train, {x:x_train, y:y_train})

    curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x:x_train, y:y_train})
    print("W:{}    b:{}    loss:{}".format(curr_W, curr_b, curr_loss))

W:[-0.9999969]    b:[0.9999908]    loss:5.699973826267524e-11


In [17]:
a = tf.random_uniform([3])
b = tf.random_normal([3])
c = tf.zeros(5)
d = tf.zeros((2,3))
with tf.Session() as sess:
    print(a, sess.run(a))
    print(b, sess.run(b))
    print(c, sess.run(c))
    print(d, sess.run(d))

Tensor("random_uniform_8:0", shape=(3,), dtype=float32) [0.4788308  0.25787294 0.5310029 ]
Tensor("random_normal_8:0", shape=(3,), dtype=float32) [ 0.951404   -0.18839644  0.91052896]
Tensor("zeros_8:0", shape=(5,), dtype=float32) [0. 0. 0. 0. 0.]
Tensor("zeros_9:0", shape=(2, 3), dtype=float32) [[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
my_graph = tf.Graph()
with tf.Session(graph=my_graph) as sess:
    x = tf.constant([1,3,6])
    y = tf.constant([1,1,1])
    op = x+y                      # or tf.add(x,y)
    print(sess.run(op))

[2 4 7]
